services:
  elastic-search-foundation:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    container_name: elastic-search-foundation
    restart: unless-stopped
    mem_limit: 1073741824
    volumes:
      - vol-elastic-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      #- 9300:9300
    environment:
      - node.name=elastic-search
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_PASSWORD=A$ur@-chUrn
      #- xpack.security.transport.ssl.enabled=true
    networks:
      - net-amrita
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  net-amrita:
    external: true
    name: net-amrita

volumes:
  vol-elastic-data:
    driver: local
    name: vol-elastic-data